# Streamlit Configuration File

# General Configuration
[server]
# headless = true
# port = 8501
# enableCORS = false
# enableXsrfProtection = false

# Theme Configuration
[theme]
base = "dark"  # Options: 'light', 'dark', 'purple'
primaryColor = "#27AE60"  # Primary button color
backgroundColor = "#2C3E50"  # App background color
secondaryBackgroundColor = "#34495E"  # Sidebar background color
textColor = "#ECF0F1"  # Text color
